#!/usr/bin/env node
/**
 * memstore-prompt: Claude Code UserPromptSubmit hook
 *
 * On each user message:
 *   1. Sends the prompt to memstored's /v1/recall for fact-based context injection.
 *   2. Fetches any pending context hints generated by the Ollama pipeline at the
 *      end of the previous session, injects them, and marks them consumed.
 *
 * Both fetches run in parallel. Either can fail independently without blocking.
 * Silently exits 0 on any error so it never blocks a session.
 */

const MEMSTORED_URL = process.env.MEMSTORED_URL || '__MEMSTORED_URL__';
const MIN_WORDS = 5;
const RECALL_LIMIT = 5;
const RECALL_BUDGET = 2000;
const MAX_HINTS = 2;

let input = {};
try {
  const raw = await stdinText();
  input = JSON.parse(raw);
} catch {
  // No stdin or invalid JSON — proceed with empty input.
}

const prompt = (input.prompt || '').trim();
const sessionId = input.session_id || input.sessionId || '';
const cwd = input.cwd || input.directory || '';

// Recall requires a substantive prompt; hints are always fetched when CWD is set.
const words = prompt.split(/\s+/).filter(Boolean);
const promptIsSubstantial = words.length >= MIN_WORDS && !prompt.startsWith('/');

// Run recall and hint fetches in parallel.
const [recallResult, hintsResult] = await Promise.allSettled([
  promptIsSubstantial ? fetchRecall(prompt, sessionId, cwd) : Promise.resolve(''),
  (sessionId || cwd) ? fetchHints(sessionId, cwd) : Promise.resolve([]),
]);

const recallContext = recallResult.status === 'fulfilled' ? (recallResult.value || '') : '';
const hints = hintsResult.status === 'fulfilled' ? (hintsResult.value || []) : [];

// Consume hints fire-and-forget — don't block the response.
if (hints.length > 0) {
  consumeHints(hints, sessionId).catch(() => {});
}

// Build additionalContext from both sources.
let additionalContext = '';

if (hints.length > 0) {
  const hintTexts = hints.map(h => h.hint_text).join('\n\n');
  additionalContext += `<memstore-hints>\n${hintTexts}\n</memstore-hints>\n`;
}
if (recallContext) {
  additionalContext += `<memstore-recall>\n${recallContext}\n</memstore-recall>\n`;
}

if (!additionalContext && !promptIsSubstantial) {
  console.log(JSON.stringify({ continue: true }));
  process.exit(0);
}

console.log(JSON.stringify({
  continue: true,
  ...(additionalContext && {
    hookSpecificOutput: {
      hookEventName: 'UserPromptSubmit',
      additionalContext: additionalContext.trim(),
    },
  }),
}));

// --- helpers ---

async function fetchRecall(prompt, sessionId, cwd) {
  const resp = await fetch(`${MEMSTORED_URL}/v1/recall`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ prompt, session_id: sessionId, cwd, limit: RECALL_LIMIT, budget: RECALL_BUDGET }),
    signal: AbortSignal.timeout(3000),
  });
  if (!resp.ok) return '';
  const result = await resp.json();
  return (result.context || '').trim();
}

async function fetchHints(sessionId, cwd) {
  const params = new URLSearchParams();
  if (sessionId) params.set('session_id', sessionId);
  if (cwd) params.set('cwd', cwd);
  const resp = await fetch(
    `${MEMSTORED_URL}/v1/context/hints?${params}`,
    { signal: AbortSignal.timeout(2000) },
  );
  if (!resp.ok) return [];
  const hints = await resp.json();
  return Array.isArray(hints) ? hints.slice(0, MAX_HINTS) : [];
}

async function consumeHints(hints, sessionId) {
  await Promise.allSettled(hints.map(async (h, rank) => {
    // Mark consumed so it doesn't reappear next prompt.
    await fetch(`${MEMSTORED_URL}/v1/context/hints/${h.id}/consume`, {
      method: 'POST',
      signal: AbortSignal.timeout(2000),
    });
    // Record injection with rank for position-bias tracking (memory_rate_context).
    if (sessionId) {
      await fetch(`${MEMSTORED_URL}/v1/context/injections`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ session_id: sessionId, ref_id: String(h.id), ref_type: 'hint', rank }),
        signal: AbortSignal.timeout(2000),
      });
    }
  }));
}

async function stdinText() {
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  return Buffer.concat(chunks).toString('utf-8');
}
