#!/usr/bin/env node
/**
 * memstore-prompt: Claude Code UserPromptSubmit hook
 *
 * On each user message:
 *   1. Sends the prompt to memstored's /v1/recall for fact-based context injection.
 *   2. Fetches any pending context hints generated by the Ollama pipeline at the
 *      end of the previous session, injects them, and marks them consumed. The
 *      daemon scores each hint against the prompt and renders the relevant ones
 *      already fenced (POST /v1/context/hints/render); this hook never builds a
 *      hint block from raw text.
 *
 * Both fetches run in parallel. Either can fail independently without blocking.
 * Silently exits 0 on any error so it never blocks a session.
 */

import { authHeaders, reportRefusal, warnOnce } from './memstore-auth.mjs';

const MEMSTORED_URL = process.env.MEMSTORED_URL || '__MEMSTORED_URL__';
const MIN_WORDS = 5;
const RECALL_LIMIT = 5;
const RECALL_BUDGET = 2000;
const MAX_HINTS = 2;
const NO_HINTS = { context: '', ids: [] };

let input = {};
try {
  const raw = await stdinText();
  input = JSON.parse(raw);
} catch {
  // No stdin or invalid JSON -- proceed with empty input.
}

const prompt = (input.prompt || '').trim();
const sessionId = input.session_id || input.sessionId || '';
const cwd = input.cwd || input.directory || '';

// Both recall and hints need a substantive prompt. A hint is shown only when
// the daemon judges it relevant to what was asked (#221), and a two-word prompt
// gives it nothing to judge against; the hint stays pending for a later prompt.
const words = prompt.split(/\s+/).filter(Boolean);
const promptIsSubstantial = words.length >= MIN_WORDS && !prompt.startsWith('/');

// Run recall and hint fetches in parallel.
const [recallResult, hintsResult] = await Promise.allSettled([
  promptIsSubstantial ? fetchRecall(prompt, sessionId, cwd) : Promise.resolve(''),
  promptIsSubstantial && (sessionId || cwd) ? fetchHints(prompt, sessionId, cwd) : Promise.resolve(NO_HINTS),
]);

const recallContext = recallResult.status === 'fulfilled' ? (recallResult.value || '') : '';
const hints = hintsResult.status === 'fulfilled' ? (hintsResult.value || NO_HINTS) : NO_HINTS;

// A transport failure is worth one line on stderr: the hook still exits 0,
// but "the daemon was unreachable" must not read the same as "nothing matched".
for (const [name, r] of [['recall', recallResult], ['hints', hintsResult]]) {
  if (r.status === 'rejected') {
    warnOnce(`memstore-prompt: ${name} failed: ${r.reason?.cause?.message || r.reason?.message || r.reason}`);
  }
}

// Consume hints fire-and-forget -- don't block the response.
if (hints.ids.length > 0) {
  consumeHints(hints.ids, sessionId).catch(() => {});
}

// Build additionalContext from both sources.
let additionalContext = '';

if (hints.context) {
  additionalContext += `<memstore-hints>\n${hints.context}\n</memstore-hints>\n`;
}
if (recallContext) {
  additionalContext += `<memstore-recall>\n${recallContext}\n</memstore-recall>\n`;
}

if (!additionalContext && !promptIsSubstantial) {
  console.log(JSON.stringify({ continue: true }));
  process.exit(0);
}

console.log(JSON.stringify({
  continue: true,
  ...(additionalContext && {
    hookSpecificOutput: {
      hookEventName: 'UserPromptSubmit',
      additionalContext: additionalContext.trim(),
    },
  }),
}));

// --- helpers ---

async function fetchRecall(prompt, sessionId, cwd) {
  const resp = await fetch(`${MEMSTORED_URL}/v1/recall`, {
    method: 'POST',
    headers: { ...authHeaders(), 'Content-Type': 'application/json' },
    body: JSON.stringify({ prompt, session_id: sessionId, cwd, limit: RECALL_LIMIT, budget: RECALL_BUDGET }),
    // Recall reranks its candidate pool on the daemon (CPU cross-encoder), which
    // runs a few seconds; allow headroom over the measured ~3.8s peak so reranked
    // context actually lands instead of being aborted. Kept just under the 5s
    // hook process timeout (setup_cmd.go) so a slow recall aborts gracefully here
    // (empty context) rather than the whole hook being killed. The daemon's recall
    // pool (RERANK_RECALL_CANDIDATES / _DOC_BYTES) is sized to stay under this.
    signal: AbortSignal.timeout(4500),
  });
  if (!resp.ok) {
    reportRefusal('memstore-prompt', resp);
    return '';
  }
  const result = await resp.json();
  return (result.context || '').trim();
}

async function fetchHints(prompt, sessionId, cwd) {
  const resp = await fetch(`${MEMSTORED_URL}/v1/context/hints/render`, {
    method: 'POST',
    headers: { ...authHeaders(), 'Content-Type': 'application/json' },
    // The prompt goes in the body, not the query string, so it stays out of
    // access logs. The daemon embeds it and the pending hints before answering,
    // so this allows more than a plain read; it runs alongside recall, inside
    // the same 5s hook budget.
    body: JSON.stringify({ session_id: sessionId, cwd, prompt, limit: MAX_HINTS }),
    signal: AbortSignal.timeout(4000),
  });
  // 404: a daemon with no render endpoint, which only has the raw list;
  // building a block from that would inject model-written text unfenced
  // (#219). 405: one whose render endpoint is GET-only and cannot judge a hint
  // against the prompt; falling back to GET would inject hints unscored (#221).
  // Either way, skip hints until the daemon is upgraded.
  if (resp.status === 404 || resp.status === 405) {
    warnOnce('memstore-prompt: memstored cannot score hints against the prompt (POST /v1/context/hints/render); hints skipped until it is upgraded');
    return NO_HINTS;
  }
  if (!resp.ok) {
    reportRefusal('memstore-prompt', resp);
    return NO_HINTS;
  }
  const body = await resp.json();
  const context = typeof body?.context === 'string' ? body.context.trim() : '';
  const ids = Array.isArray(body?.ids) ? body.ids.filter(Number.isInteger) : [];
  if (!context || ids.length === 0) return NO_HINTS;
  return { context, ids };
}

async function consumeHints(ids, sessionId) {
  await Promise.allSettled(ids.map(async (id, rank) => {
    // Mark consumed so it doesn't reappear next prompt.
    await fetch(`${MEMSTORED_URL}/v1/context/hints/${id}/consume`, {
      method: 'POST',
      headers: authHeaders(),
      signal: AbortSignal.timeout(2000),
    });
    // Record injection with rank for position-bias tracking (memory_rate_context).
    if (sessionId) {
      await fetch(`${MEMSTORED_URL}/v1/context/injections`, {
        method: 'POST',
        headers: { ...authHeaders(), 'Content-Type': 'application/json' },
        body: JSON.stringify({ session_id: sessionId, ref_id: String(id), ref_type: 'hint', rank }),
        signal: AbortSignal.timeout(2000),
      });
    }
  }));
}

async function stdinText() {
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  return Buffer.concat(chunks).toString('utf-8');
}
